const plan={weeks:[
{n:1,title:'Foundations',focus:'DSA + system design fundamentals + backend scalability',items:['Arrays & hashing','Two pointers & sliding window','Scalability basics','Caching fundamentals','Project deep dive #1']},
{n:2,title:'Java + MySQL/TiDB',focus:'Java concurrency, JVM, database internals',items:['Java collections & internals','Threads & concurrency','JVM memory & GC','MySQL indexes & EXPLAIN','Transactions & isolation','TiDB architecture']},
{n:3,title:'Redis + Caching',focus:'Low-latency data access and distributed patterns',items:['Redis data structures','Cache-aside','TTL & eviction','Cache stampede','Hot keys','Rate limiting']},
{n:4,title:'Distributed Systems',focus:'Consistency, failure and coordination',items:['CAP','Replication','Quorums','Idempotency','Retries & backoff','Circuit breakers']},
{n:5,title:'Kafka I',focus:'Core Kafka architecture',items:['Topics & partitions','Producers','Consumer groups','Offsets','Ordering','Replication']},
{n:6,title:'Kafka II',focus:'Reliability and production Kafka',items:['Delivery semantics','Retries','Dead-letter queues','Consumer lag','Rebalancing','Idempotent consumers']},
{n:7,title:'Elasticsearch',focus:'Search architecture and scaling',items:['Inverted index','Mappings & analyzers','Shards & replicas','Refresh','Aggregations','Relevance']},
{n:8,title:'CDC + Data Consistency',focus:'TiDB/MySQL → Kafka → Elasticsearch',items:['Transactional outbox','CDC concepts','Replay','Deduplication','Ordering','Reconciliation']},
{n:9,title:'LLD',focus:'Clean, extensible object-oriented design',items:['SOLID','Composition','Interfaces','Dependency injection','Parking lot','Notification framework']},
{n:10,title:'Concurrency',focus:'Java concurrency and production behavior',items:['Executors','Locks','Atomic operations','Deadlocks','Thread pools','Concurrent collections']},
{n:11,title:'Production Engineering',focus:'Debugging, reliability and operations',items:['Latency debugging','CPU/memory diagnosis','DB bottlenecks','Kafka lag','Observability','Incident response']},
{n:12,title:'Project Deep Dives',focus:'Turn real work into SDE 3 evidence',items:['Architecture #1','Architecture #2','Architecture #3','Trade-offs','Failures','Impact metrics']},
{n:13,title:'Interview Mode I',focus:'Coding + system design mocks',items:['2 coding mocks','2 system-design mocks','1 LLD mock','Behavioral stories']},
{n:14,title:'Interview Mode II',focus:'Weak-area correction',items:['Timed coding','Deep system design','Project defense','Leadership']},
{n:15,title:'Target Company Prep',focus:'Company-specific loops and calibration',items:['Role research','Question patterns','Mock loop','Resume/project alignment']},
{n:16,title:'Final Readiness',focus:'Full SDE 3 simulation',items:['Full loop','Final weak areas','Story refinement','Interview logistics']}
],
topics:{
'DSA':{goal:'180–200 quality problems',items:['Arrays & hashing','Two pointers','Sliding window','Binary search','Trees','Graphs','Heaps','Intervals','Monotonic stack','Backtracking','Dynamic programming']},
'Java & Spring':{goal:'Senior-level Java/backend depth',items:['Collections internals','JVM memory','GC','Java Memory Model','Threads','Executors','CompletableFuture','Locks & atomics','Spring DI','Transactions','Connection/thread pools']},
'MySQL & TiDB':{goal:'Database design and scaling',items:['Indexes','EXPLAIN','Query optimization','Transactions','Isolation levels','Locks & deadlocks','MVCC','Replication','Partitioning','Sharding','TiDB architecture']},
'Redis':{goal:'Caching + distributed primitives',items:['Strings/Hash/Set/ZSet','Cache-aside','TTL','Eviction','Stampede','Hot keys','Rate limiting','Distributed locks','Streams']},
'Kafka':{goal:'Production-grade event streaming',items:['Topics','Partitions','Producers','Consumer groups','Offsets','Ordering','Replication','Delivery semantics','Retries','DLQ','Consumer lag','Idempotency']},
'Elasticsearch':{goal:'Search architecture',items:['Inverted index','Mappings','Analyzers','Queries','Aggregations','Shards','Replicas','Refresh','Reindexing','Scaling']},
'Aerospike':{goal:'Distributed key-value architecture',items:['Data model','Namespaces','Sets','Records','Bins','Partitions','Replication','Consistency','TTL','Rebalancing','When to choose it']},
'LLD & Concurrency':{goal:'Clean design + safe concurrent code',items:['SOLID','Composition','Interfaces','DI','Design patterns','Parking lot','Scheduler','Rate limiter','Thread safety','Deadlocks']},
'System Design':{goal:'60-minute senior design conversations',items:['Requirements','Estimation','APIs','Data model','Caching','Queues','Partitioning','Consistency','Reliability','Observability','Cost','Failure modes']},
'Leadership & Behavioral':{goal:'8–10 strong stories',items:['Ownership','Conflict','Influence','Mentoring','Failure','Ambiguity','Technical decision','Incident','Cost/performance win','Cross-team work']}
}}
};

const stateKey='sde3-prep-checks-v1';
let checks=JSON.parse(localStorage.getItem(stateKey)||'{}');
const navItems=[['dashboard','Dashboard'],['today','Today'],['weeks','16-Week Plan'],['topics','Topics & Checklists'],['projects','Projects'],['mocks','Mock Interviews']];
let current=location.hash.replace('#','')||'dashboard';
const nav=document.getElementById('nav'),view=document.getElementById('view'),title=document.getElementById('pageTitle');
nav.innerHTML=navItems.map(([id,label])=>`<button class="nav-btn" data-view="${id}">${label}</button>`).join('');
nav.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;location.hash=b.dataset.view;render()});
window.addEventListener('hashchange',render);
document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset all local checklist progress?')){checks={};save();render()}};
document.getElementById('todayDate').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date());
function save(){localStorage.setItem(stateKey,JSON.stringify(checks))}
function key(group,item){return `${group}::${item}`}
function isDone(group,item){return !!checks[key(group,item)]}
function toggle(group,item){const k=key(group,item);checks[k]=!checks[k];save();render()}
function pct(group,items){if(!items.length)return 0;return Math.round(items.filter(x=>isDone(group,x)).length/items.length*100)}
function allItems(){return Object.entries(plan.topics).flatMap(([g,v])=>v.items.map(i=>[g,i]))}
function overall(){const a=allItems();return Math.round(a.filter(([g,i])=>isDone(g,i)).length/a.length*100)}
function taskList(group,items){return `<div class="checklist">${items.map(i=>`<label><input type="checkbox" ${isDone(group,i)?'checked':''} onchange="toggle('${esc(group)}','${esc(i)}')"><span>${isDone(group,i)?'<s>':''}${i}${isDone(group,i)?'</s>':''}</span></label>`).join('')}</div>`}
function esc(s){return s.replaceAll('\\','\\\\').replaceAll("'","\\'")}
function render(){current=location.hash.replace('#','')||'dashboard';document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===current));title.textContent=navItems.find(x=>x[0]===current)?.[1]||'Dashboard';({dashboard:renderDashboard,today:renderToday,weeks:renderWeeks,topics:renderTopics,projects:renderProjects,mocks:renderMocks}[current]||renderDashboard)()}
function renderDashboard(){const p=overall();const topicCards=Object.entries(plan.topics).slice(0,6).map(([g,v])=>{const q=pct(g,v.items);return `<div class="card"><h3>${g}</h3><div class="muted">${v.goal}</div><div class="metric">${q}%</div><div class="bar"><i style="width:${q}%"></i></div></div>`}).join('');view.innerHTML=`<div class="hero"><div><div class="eyebrow">Current target</div><h2>Become SDE 3 interview-ready</h2><p>16 weeks focused on system design, distributed backend engineering, Java, DSA, LLD, leadership and your real production experience.</p><div class="callout" style="margin-top:18px">Your stack: Java · Spring Boot · MySQL · TiDB/Rigel · Elasticsearch · Redis · Kafka · Aerospike</div></div><div class="progress-ring"><div class="ring" style="--p:${p*3.6}deg"><span>${p}%</span></div></div></div><h2 class="section-title">Skill dashboard</h2><div class="grid">${topicCards}</div><h2 class="section-title">This week's target</h2><div class="card"><strong>Week 1 — Foundations</strong><p class="muted">DSA + system-design fundamentals + backend scalability. Heavy work belongs on the weekend; weekdays stay light around office.</p>${taskList('Week 1',['Arrays & hashing','Two pointers & sliding window','Scalability basics','Caching fundamentals','Project deep dive #1'])}</div>`}
function renderToday(){const day=new Date().getDay();let tasks=day===0?['DSA mock','System-design mock','LLD practice','Behavioral story','Weekly review']:day===6?['2–3 DSA problems','System-design deep work','LLD practice','Review mistakes']:day===5?['Light revision','Project/behavioral story']:['DSA practice','System-design concept','Backend concept'];view.innerHTML=`<div class="card"><div class="eyebrow">Today</div><h2>${new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</h2><p class="muted">Keep weekdays manageable. Push the deep work to Saturday and Sunday.</p>${taskList('Today',tasks)}</div><h2 class="section-title">Recommended focus</h2><div class="grid"><div class="card"><h3>DSA</h3><p class="muted">Pattern recognition over volume. Explain the approach before coding.</p></div><div class="card"><h3>System design</h3><p class="muted">Requirements → scale → architecture → bottlenecks → failures → trade-offs.</p></div><div class="card"><h3>Backend</h3><p class="muted">Connect what you study to real production systems you have worked on.</p></div></div>`}
function renderWeeks(){view.innerHTML=`<div class="callout">The roadmap is deliberately backend-heavy. SDE 3 readiness is not just harder DSA: system design, distributed systems, production judgment, ownership and communication carry major weight.</div><h2 class="section-title">16 weeks</h2><div class="week-list">${plan.weeks.map(w=>{const items=plan.topics[w.title]?.items||w.items;const q=pct(w.title,items);return `<div class="week" onclick="location.hash='week-${w.n}'"><div class="week-head"><div><h3>Week ${w.n} — ${w.title}</h3><small>${w.focus}</small></div><strong>${q}%</strong></div><div class="bar"><i style="width:${q}%"></i></div></div>`}).join('')}</div>`}
function renderTopics(){view.innerHTML=`<div class="topic-grid">${Object.entries(plan.topics).map(([g,v])=>{const q=pct(g,v.items);return `<div class="topic-card"><div class="topic-head"><h3>${g}</h3><span class="score">${q}%</span></div><p class="muted">${v.goal}</p>${taskList(g,v.items)}</div>`}).join('')}</div>`}
function renderProjects(){view.innerHTML=`<div class="two-col"><div class="card"><h3>Project Deep Dive #1</h3><p class="muted">Document one major production project: problem, scale, architecture, your exact contribution, decisions, alternatives, failures, impact and what you would redesign.</p>${taskList('Projects #1',['Problem & requirements','Scale / metrics','Architecture diagram','My exact contribution','Key trade-offs','Failure / incident','Impact metrics','What I would redesign'])}</div><div class="card"><h3>Project Deep Dive #2</h3><p class="muted">Prepare a second project with enough depth to survive a 30–45 minute interviewer drill-down.</p>${taskList('Projects #2',['Problem & requirements','Scale / metrics','Architecture diagram','My exact contribution','Key trade-offs','Failure / incident','Impact metrics','What I would redesign'])}</div></div><h2 class="section-title">Rule</h2><div class="callout">Never put confidential company architecture, code, credentials, customer data or internal URLs into this GitHub-backed dashboard. Keep sensitive details abstracted.</div>`}
function renderMocks(){view.innerHTML=`<div class="grid"><div class="card"><h3>Coding mocks</h3><p class="muted">Target from Week 9: 2/week. 45–60 minutes. Clarify → approach → code → test → complexity.</p></div><div class="card"><h3>System-design mocks</h3><p class="muted">Target from Week 9: 2/week. Practice the conversation, not a memorized diagram.</p></div><div class="card"><h3>LLD mocks</h3><p class="muted">Target: 1/week. Focus on clean abstractions, extensibility, concurrency and testability.</p></div></div><h2 class="section-title">Mock log</h2><div class="card">${taskList('Mocks',['Coding mock #1','Coding mock #2','System design mock #1','System design mock #2','LLD mock','Behavioral/project mock','Weekly review'])}</div>`}
render();