const WEEKS = [
  {
    n: 1, title: 'Foundations', focus: 'DSA + system design fundamentals + backend scalability', weekend: 'Sat/Sun: 5–7h each',
    days: {
      Mon: { focus: 'DSA — Arrays + Hashing', time: '60 min', learn: ['HashMap / HashSet and expected O(1) lookup', 'Frequency counting', 'Canonical keys for grouping'], problems: [['Two Sum','Easy','https://leetcode.com/problems/two-sum/'],['Contains Duplicate','Easy','https://leetcode.com/problems/contains-duplicate/'],['Valid Anagram','Easy','https://leetcode.com/problems/valid-anagram/'],['Group Anagrams','Medium','https://leetcode.com/problems/group-anagrams/'],['Product of Array Except Self','Medium','https://leetcode.com/problems/product-of-array-except-self/']], resources: [['NeetCode Roadmap','https://neetcode.io/roadmap']], output: 'Write 3 notes: when hashing helps, how to choose a canonical key, and the memory/time trade-off.' },
      Tue: { focus: 'System Design — Scalability Basics', time: '75 min', learn: ['Vertical vs horizontal scaling', 'Stateless services', 'Load balancers', 'Latency vs throughput', 'Availability', 'Sync vs async', 'Cache-aside'], problems: [['URL Shortener — design exercise','System Design','https://github.com/donnemartin/system-design-primer#system-design-topics-start-here']], resources: [['System Design Primer — start here','https://github.com/donnemartin/system-design-primer#system-design-topics-start-here'],['System Design Primer — scalability','https://github.com/donnemartin/system-design-primer#scalability']], output: 'Draw Client → Load Balancer → App → Cache → DB and explain what changes at 10× traffic.' },
      Wed: { focus: 'DSA — Two Pointers + Sliding Window', time: '60 min', learn: ['Two pointers for converging or independent traversal', 'Sliding-window state maintenance', 'Avoid recomputing the entire window', 'Say the pattern before you code'], problems: [['Valid Palindrome','Easy','https://leetcode.com/problems/valid-palindrome/'],['Two Sum II — Input Array Is Sorted','Medium','https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/'],['3Sum','Medium','https://leetcode.com/problems/3sum/'],['Longest Substring Without Repeating Characters','Medium','https://leetcode.com/problems/longest-substring-without-repeating-characters/'],['Longest Repeating Character Replacement','Medium','https://leetcode.com/problems/longest-repeating-character-replacement/']], resources: [['NeetCode Roadmap','https://neetcode.io/roadmap'],['LeetCode Study Plans','https://leetcode.com/studyplan/']], output: 'For each problem, identify the trigger for two pointers vs sliding window. Then explain one solution aloud without notes.' },
      Thu: { focus: 'Backend — Scalability in Java/Spring', time: '75 min', learn: ['Load-balancing strategies', 'Spring request/thread pools', 'DB connection pools', 'Timeouts', 'Retries and retry storms', 'Rate limiting basics'], problems: [['Rate limiter — design exercise','System Design','https://github.com/donnemartin/system-design-primer#load-balancer']], resources: [['System Design Primer — load balancer','https://github.com/donnemartin/system-design-primer#load-balancer']], output: 'Explain why retries can amplify an outage and how timeouts + backoff + rate limits help.' },
      Fri: { focus: 'Project Deep Dive #1', time: '45 min', learn: ['Problem and requirements', 'Scale and metrics', 'Architecture', 'Your exact contribution', 'Trade-offs', 'Failure / incident', 'Impact', 'What you would redesign'], problems: [], resources: [], output: 'Create a one-page project story you can defend for 30 minutes.' },
      Sat: { focus: 'Deep Work — DSA + URL Shortener', time: '5–7h', learn: ['Review Week 1 patterns', 'Do a complete URL-shortener design', 'Estimate RPS/storage', 'Discuss caching, DB, ID generation and failures', 'LLD: Parking Lot'], problems: [['Best Time to Buy and Sell Stock','Easy','https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'],['Maximum Subarray','Medium','https://leetcode.com/problems/maximum-subarray/'],['Longest Consecutive Sequence','Medium','https://leetcode.com/problems/longest-consecutive-sequence/'],['Subarray Sum Equals K','Medium','https://leetcode.com/problems/subarray-sum-equals-k/']], resources: [['System Design Primer','https://github.com/donnemartin/system-design-primer']], output: 'One complete 45–60 minute design plus a written list of everything you forgot.' },
      Sun: { focus: 'Mock + LLD + Weekly Review', time: '5–7h', learn: ['Timed coding mock', 'Rate-limiter design', 'SOLID, composition and interfaces', 'Two behavioral stories', 'Weekly review and weak-area diagnosis'], problems: [['Longest Substring Without Repeating Characters','Medium','https://leetcode.com/problems/longest-substring-without-repeating-characters/'],['Merge Intervals','Medium','https://leetcode.com/problems/merge-intervals/'],['Top K Frequent Elements','Medium','https://leetcode.com/problems/top-k-frequent-elements/'],['Binary Search','Easy','https://leetcode.com/problems/binary-search/']], resources: [['System Design Primer','https://github.com/donnemartin/system-design-primer']], output: 'Score yourself 1–5 on DSA, system design, backend, LLD, communication and project depth.' }
    }
  },
  {
    n: 2, title: 'Java + MySQL/TiDB', focus: 'Java concurrency, JVM and database internals', weekend: 'Sat/Sun: 5–7h each',
    days: {
      Mon: { focus: 'Java — Collections Internals', time: '60 min', learn: ['ArrayList vs LinkedList', 'HashMap internals', 'equals/hashCode', 'TreeMap/TreeSet', 'ConcurrentHashMap'], problems: [['LRU Cache','Medium','https://leetcode.com/problems/lru-cache/']], resources: [['HashMap Java API','https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/HashMap.html']], output: 'Explain collisions, resizing and why mutable keys are dangerous.' },
      Tue: { focus: 'Java — Threads + Concurrency', time: '75 min', learn: ['Thread vs task', 'synchronized', 'volatile', 'locks', 'Executors', 'race conditions', 'deadlocks'], problems: [['Print in Order','Easy','https://leetcode.com/problems/print-in-order/']], resources: [['Java concurrency package','https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/package-summary.html']], output: 'Explain one race condition and one deadlock scenario.' },
      Wed: { focus: 'JVM Memory + GC', time: '60 min', learn: ['Heap, stack, metaspace', 'Allocation pressure', 'GC pauses', 'Memory leaks', 'Production diagnosis'], problems: [], resources: [['Java GC Tuning','https://docs.oracle.com/en/java/javase/21/gctuning/']], output: 'Explain why memory can grow even in a garbage-collected process.' },
      Thu: { focus: 'MySQL — Indexes + EXPLAIN', time: '75 min', learn: ['B-tree indexes', 'Composite index order', 'Covering indexes', 'Selectivity', 'EXPLAIN basics', 'Avoiding full scans'], problems: [['SQL 50','Study plan','https://leetcode.com/studyplan/top-sql-50/']], resources: [['MySQL EXPLAIN','https://dev.mysql.com/doc/refman/8.4/en/explain.html']], output: 'Take one real query and explain the best index for it.' },
      Fri: { focus: 'Transactions + Isolation', time: '45 min', learn: ['ACID', 'Read committed', 'Repeatable read', 'Serializable', 'Locks', 'Deadlocks', 'MVCC'], problems: [], resources: [['MySQL isolation levels','https://dev.mysql.com/doc/refman/8.4/en/innodb-transaction-isolation-levels.html']], output: 'Explain a lost update and how isolation/locking prevents it.' },
      Sat: { focus: 'Deep Work — Java + MySQL/TiDB', time: '5–7h', learn: ['Concurrency coding', 'JVM troubleshooting', 'MySQL query tuning', 'TiDB architecture', 'Distributed SQL trade-offs'], problems: [['LRU Cache','Medium','https://leetcode.com/problems/lru-cache/'],['Number of Islands','Medium','https://leetcode.com/problems/number-of-islands/']], resources: [['TiDB Architecture','https://docs.pingcap.com/tidb/stable/tidb-architecture/'],['InnoDB Introduction','https://dev.mysql.com/doc/refman/8.4/en/innodb-introduction.html']], output: 'Explain when TiDB is preferable to a single MySQL deployment and what trade-offs it introduces.' },
      Sun: { focus: 'Mocks + Database Design', time: '5–7h', learn: ['1 coding mock', '1 database design mock', 'Deadlock debugging', 'Project architecture drill-down'], problems: [['Merge K Sorted Lists','Hard','https://leetcode.com/problems/merge-k-sorted-lists/'],['Number of Islands','Medium','https://leetcode.com/problems/number-of-islands/']], resources: [['MySQL Reference','https://dev.mysql.com/doc/refman/8.4/en/']], output: 'Finish with 5 database questions you cannot yet answer.' }
    }
  },
  { n: 3, title: 'Redis + Caching', focus: 'Redis data structures, cache design and distributed primitives', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 4, title: 'Distributed Systems', focus: 'Consistency, replication, coordination and failure', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 5, title: 'Kafka I', focus: 'Topics, partitions, producers and consumers', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 6, title: 'Kafka II', focus: 'Delivery semantics, lag, retries, DLQs and rebalancing', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 7, title: 'Elasticsearch', focus: 'Search internals, shards, replicas and scaling', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 8, title: 'CDC + Data Consistency', focus: 'MySQL/TiDB → Kafka → Elasticsearch', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 9, title: 'LLD', focus: 'SOLID, composition, interfaces and extensibility', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 10, title: 'Concurrency', focus: 'Executors, locks, atomics, deadlocks and thread pools', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 11, title: 'Production Engineering', focus: 'Debugging, reliability and observability', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 12, title: 'Project Deep Dives', focus: 'Turn real work into SDE 3 evidence', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 13, title: 'Interview Mode I', focus: 'Coding + system-design + LLD mocks', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 14, title: 'Interview Mode II', focus: 'Weak-area correction and targeted mocks', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 15, title: 'Target Company Prep', focus: 'Company-specific loops and calibration', weekend: 'Sat/Sun: 5–7h each', days: {} },
  { n: 16, title: 'Final Readiness', focus: 'Full SDE 3 simulation', weekend: 'Sat/Sun: 5–7h each', days: {} }
];

const TOPICS = {
  'DSA': ['Arrays & hashing','Two pointers','Sliding window','Binary search','Trees','Graphs','Heaps','Intervals','Monotonic stack','Backtracking','Dynamic programming'],
  'Java & Spring': ['Collections internals','JVM memory','GC','Java Memory Model','Threads','Executors','CompletableFuture','Locks & atomics','Spring DI','Transactions','Connection/thread pools'],
  'MySQL & TiDB': ['Indexes','EXPLAIN','Query optimization','Transactions','Isolation levels','Locks & deadlocks','MVCC','Replication','Partitioning','Sharding','TiDB architecture'],
  'Redis': ['Strings/Hash/Set/ZSet','Cache-aside','TTL','Eviction','Cache stampede','Hot keys','Rate limiting','Distributed locks','Streams'],
  'Kafka': ['Topics','Partitions','Producers','Consumer groups','Offsets','Ordering','Replication','Delivery semantics','Retries','DLQ','Consumer lag','Idempotency'],
  'Elasticsearch': ['Inverted index','Mappings','Analyzers','Queries','Aggregations','Shards','Replicas','Refresh','Reindexing','Scaling'],
  'Aerospike': ['Data model','Namespaces','Sets','Records','Bins','Partitions','Replication','Consistency','TTL','Rebalancing','When to choose it'],
  'LLD & Concurrency': ['SOLID','Composition','Interfaces','DI','Design patterns','Parking lot','Scheduler','Rate limiter','Thread safety','Deadlocks'],
  'System Design': ['Requirements','Estimation','APIs','Data model','Caching','Queues','Partitioning','Consistency','Reliability','Observability','Cost','Failure modes'],
  'Leadership & Behavioral': ['Ownership','Conflict','Influence','Mentoring','Failure','Ambiguity','Technical decision','Incident','Cost/performance win','Cross-team work']
};

const MATERIALS = {
  1: [
    ['Monday','Arrays + Hashing','5 DSA problems + pattern notes'],['Tuesday','Scalability fundamentals','Read scalability + design URL shortener'],['Wednesday','Two pointers + sliding window','5 DSA problems + explain patterns'],['Thursday','Backend scalability','Timeouts, retries, rate limiting'],['Friday','Project deep dive','Architecture + ownership + impact'],['Saturday','Deep work','4 DSA + URL shortener + Parking Lot'],['Sunday','Mock day','4 DSA + rate limiter + behavioral']
  ],
  2: [
    ['Monday','Java Collections','HashMap + LRU Cache'],['Tuesday','Concurrency','Threads + synchronization'],['Wednesday','JVM + GC','Memory + GC fundamentals'],['Thursday','MySQL indexes','EXPLAIN + SQL 50'],['Friday','Transactions','Isolation + MVCC'],['Saturday','Java + DB deep work','Concurrency + MySQL/TiDB'],['Sunday','Database mock','Design + deadlock debugging']
  ],
  3: [['Monday','Redis fundamentals','Data structures + commands'],['Tuesday','Cache-aside','Hits, misses, TTL'],['Wednesday','Eviction','LRU, hot keys, stampede'],['Thursday','Rate limiting','Token bucket + Redis'],['Friday','Redis failure modes','Consistency + failover'],['Saturday','Cache-heavy design','Product catalog'],['Sunday','Mock + review','Redis architecture questions']],
  4: [['Monday','CAP','Consistency, availability, partitions'],['Tuesday','Replication','Leader/follower + failover'],['Wednesday','Quorums','Read/write quorum reasoning'],['Thursday','Idempotency','Retries + duplicate requests'],['Friday','Resilience','Circuit breakers + graceful degradation'],['Saturday','Distributed design','Failure-driven system design'],['Sunday','Mock + review','Distributed-systems drill']],
  5: [['Monday','Kafka basics','Topic, broker, partition'],['Tuesday','Consumers','Groups, offsets'],['Wednesday','Ordering','Partition keys + ordering'],['Thursday','Producers','acks, batching, retries'],['Friday','Replication','ISR + durability'],['Saturday','Kafka design','Event-driven service'],['Sunday','Mock + review','Producer/consumer interview']],
  6: [['Monday','Delivery semantics','At-most / at-least once'],['Tuesday','Idempotency','Dedup consumers'],['Wednesday','Retries','Backoff + retry topics'],['Thursday','DLQ','Poison messages'],['Friday','Consumer lag','Diagnosis + scaling'],['Saturday','Kafka reliability','Failure simulation'],['Sunday','Mock + review','Kafka production drill']],
  7: [['Monday','Inverted index','How search differs from SQL'],['Tuesday','Mappings','Keyword vs text'],['Wednesday','Analyzers','Tokenization + normalization'],['Thursday','Queries','Match, term, bool'],['Friday','Aggregations','Buckets + metrics'],['Saturday','Shards + replicas','Scaling Elasticsearch'],['Sunday','Mock + review','Search architecture']],
  8: [['Monday','Outbox','Dual-write problem'],['Tuesday','CDC','Change streams'],['Wednesday','Kafka handoff','Ordering + replay'],['Thursday','Dedup','Idempotent indexing'],['Friday','Reconciliation','Repairing divergence'],['Saturday','End-to-end design','TiDB/MySQL → Kafka → ES'],['Sunday','Mock + review','Consistency drill']],
  9: [['Monday','SOLID','Responsibilities + interfaces'],['Tuesday','Composition','Avoid rigid inheritance'],['Wednesday','Patterns','Strategy, Factory, Observer'],['Thursday','DI','Testability + wiring'],['Friday','Modeling','Entities + services'],['Saturday','Parking Lot','Full LLD'],['Sunday','Notification framework','LLD mock']],
  10: [['Monday','Executors','Thread pools'],['Tuesday','Locks','Mutex/read-write locks'],['Wednesday','Atomics','CAS + counters'],['Thursday','Deadlocks','Detection + avoidance'],['Friday','Concurrent collections','Thread-safe structures'],['Saturday','Concurrency coding','Debug concurrent code'],['Sunday','Concurrency mock','Explain thread safety']],
  11: [['Monday','Latency debugging','Trace the critical path'],['Tuesday','CPU','Profile + hot code'],['Wednesday','Memory','Heap pressure + leaks'],['Thursday','DB bottlenecks','Locks, slow queries, pool'],['Friday','Kafka lag','Throughput mismatch'],['Saturday','Incident simulation','Mitigate → root cause'],['Sunday','Observability review','Logs + metrics + traces']],
  12: [['Monday','Project #1','Problem + scale'],['Tuesday','Project #1','Architecture'],['Wednesday','Project #2','Problem + scale'],['Thursday','Project #2','Architecture'],['Friday','Project #3','Trade-offs'],['Saturday','Project defense','30–45 min drill-down'],['Sunday','Behavioral','Leadership stories']],
  13: [['Monday','Coding mock #1','Timed Medium'],['Tuesday','Design mock #1','60 min'],['Wednesday','LLD mock','45–60 min'],['Thursday','Coding mock #2','Timed Medium/Hard'],['Friday','Behavioral','Leadership stories'],['Saturday','Full mini-loop','Coding + design'],['Sunday','Review','Mistake log + weak areas']],
  14: [['Monday','Weak area #1','Targeted practice'],['Tuesday','Weak area #2','Targeted system design'],['Wednesday','Project defense','Deep dive'],['Thursday','Production debugging','Incident drill'],['Friday','Leadership','Influence + conflict'],['Saturday','Targeted mocks','Hardest areas'],['Sunday','Review','Readiness reassessment']],
  15: [['Monday','Company research','Role + level expectations'],['Tuesday','Interview loop','Coding patterns'],['Wednesday','Design calibration','Company patterns'],['Thursday','Behavioral','Values/leadership'],['Friday','Resume alignment','Project evidence'],['Saturday','Mock loop','Company simulation'],['Sunday','Review','Gap closure']],
  16: [['Monday','Final DSA','Pattern revision'],['Tuesday','Final design','One full system'],['Wednesday','Final LLD','One complete design'],['Thursday','Final backend','Kafka/Redis/DB rapid review'],['Friday','Behavioral','Stories + metrics'],['Saturday','Full loop','All interview types'],['Sunday','Final review','Logistics + confidence']]
};

const STATE_KEY = 'sde3-prep-state-v3';
let state = {checks:{}, confidence:{}};
try { state = Object.assign(state, JSON.parse(localStorage.getItem(STATE_KEY) || '{}')); } catch(e) {}
function save(){ localStorage.setItem(STATE_KEY, JSON.stringify(state)); }
function isDone(id){ return !!state.checks[id]; }
function toggle(id){ state.checks[id] = !state.checks[id]; save(); render(); }
window.togglePrep = toggle;
function esc(s){ return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'); }
function checklist(items,prefix){ return '<div class="checklist">' + items.map((x)=>{ const id=prefix+x; return '<label class="study-check"><input type="checkbox" '+(isDone(id)?'checked':'')+' onchange="togglePrep(\''+esc(id).replace(/&#39;/g,"\\'")+'\')"><span>'+esc(x)+'</span></label>'; }).join('') + '</div>'; }
function resourceLinks(arr){ if(!arr || !arr.length) return '<div class="muted">No external material required today.</div>'; return '<div class="resources">' + arr.map(r=>'<a class="resource-link" target="_blank" rel="noopener" href="'+r[1]+'">'+esc(r[0])+' ↗</a>').join('') + '</div>'; }
function problemList(arr){ if(!arr || !arr.length) return '<div class="muted">No coding problems today. Complete the study/output task instead.</div>'; return '<div class="problem-list">'+arr.map(p=>'<div class="problem-row"><div><strong>'+esc(p[0])+'</strong><span class="tag">'+esc(p[1])+'</span></div><a target="_blank" rel="noopener" href="'+p[2]+'">Open ↗</a></div>').join('')+'</div>'; }
function currentWeek(){ return 1; }
function currentDay(){ return ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][new Date().getDay()]; }
function todayMaterial(){ return WEEKS[currentWeek()-1].days[currentDay()] || WEEKS[0].days.Wed; }
function progressFor(group,items){ return items.length ? Math.round(items.filter(x=>isDone(group+'::'+x)).length/items.length*100) : 0; }
function overall(){ let total=0,done=0; Object.entries(TOPICS).forEach(([g,items])=>{total+=items.length;done+=items.filter(x=>isDone(g+'::'+x)).length;}); return Math.round(done/total*100); }
function nav(){ const current=(location.hash||'#dashboard').slice(1); const items=[['dashboard','Dashboard'],['today','Today'],['weeks','16-Week Plan'],['topics','Topics & Checklists'],['projects','Projects'],['mocks','Mock Interviews']]; document.getElementById('nav').innerHTML=items.map(x=>'<button class="nav-btn '+(current===x[0]?'active':'')+'" data-v="'+x[0]+'">'+x[1]+'</button>').join(''); document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.v;render();}); }
function headerTitle(){ const c=(location.hash||'#dashboard').slice(1); const m={dashboard:'Dashboard',today:'Today',weeks:'16-Week Plan',topics:'Topics & Checklists',projects:'Projects',mocks:'Mock Interviews'}; return m[c] || (c.startsWith('week') ? 'Week '+c.replace('week','') : 'Dashboard'); }
function renderDashboard(){
  const p=overall(); let html='<div class="hero"><div><div class="eyebrow">Backend Engineer → SDE 3</div><h2>Become SDE 3 interview-ready</h2><p>16 weeks built around your Java/Spring backend experience. Weekdays stay manageable around office; the heavy learning happens on Saturday/Sunday.</p><div class="callout light"><strong>Your stack:</strong> Java · Spring Boot · MySQL · TiDB/Rigel · Elasticsearch · Redis · Kafka · Aerospike</div></div><div class="progress-ring"><div class="ring" style="--p:'+p*3.6+'deg"><span>'+p+'%</span></div></div></div>';
  html+='<div class="grid stats"><div class="card"><div class="muted">Overall checklist</div><div class="metric">'+p+'%</div></div><div class="card"><div class="muted">DSA target</div><div class="metric">180–200</div><div class="small">quality problems</div></div><div class="card"><div class="muted">Weekly target</div><div class="metric">17–22h</div><div class="small">weekday + weekend</div></div></div>';
  html+='<h2 class="section-title">SDE 3 priority stack</h2><div class="grid">'; [['System Design','Requirements → estimates → architecture → bottlenecks → reliability → cost'],['Distributed Backend','Kafka + Redis + databases + consistency + idempotency'],['Java / Spring','JVM + concurrency + pools + transactions + production behavior'],['DSA','Pattern recognition + clean implementation'],['LLD','SOLID + composition + extensibility'],['Leadership','Ownership + influence + mentoring + incidents']].forEach(x=>html+='<div class="card"><h3>'+x[0]+'</h3><p class="muted">'+x[1]+'</p></div>'); html+='</div>';
  html+='<h2 class="section-title">Week 1 at a glance</h2><div class="card"><div class="schedule">'+['Mon · DSA — Arrays + Hashing · 60m','Tue · System Design — scalability + caching · 75m','Wed · DSA — two pointers + sliding window · 60m','Thu · Backend — timeouts + retries + rate limiting · 75m','Fri · Project deep dive #1 · 45m','Sat · DSA + URL shortener + LLD · 5–7h','Sun · mocks + review · 5–7h'].map(x=>'<div><strong>'+x.split(' · ')[0]+'</strong><span>'+x.substring(x.indexOf(' · ')+3)+'</span></div>').join('')+'</div></div>';
  html+='<h2 class="section-title">Skill progress</h2><div class="topic-grid">'; Object.entries(TOPICS).forEach(([g,items])=>{const q=progressFor(g,items);html+='<div class="topic-card"><div class="topic-head"><h3>'+g+'</h3><span class="score">'+q+'%</span></div><div class="bar"><i style="width:'+q+'%"></i></div></div>';}); html+='</div>'; document.getElementById('view').innerHTML=html;
}
function renderToday(){
  const d=todayMaterial(); const date=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
  let html='<div class="today-hero"><div><div class="eyebrow">Week '+currentWeek()+' · '+date+'</div><h2>'+esc(d.focus)+'</h2><p>Today is a focused study block. Learn → solve → explain → record the takeaway.</p></div><div class="time-pill">'+esc(d.time)+'</div></div>';
  html+='<div class="today-grid"><div><div class="card"><div class="section-kicker">1 · Study</div><h3>What to learn</h3>'+checklist(d.learn,'today-learn::')+'</div>';
  html+='<div class="card"><div class="section-kicker">2 · Practice</div><h3>Problems / exercises</h3>'+problemList(d.problems)+'</div></div>';
  html+='<div><div class="card"><div class="section-kicker">3 · Materials</div><h3>External resources</h3>'+resourceLinks(d.resources)+'</div>';
  html+='<div class="card"><div class="section-kicker">4 · Deliverable</div><h3>What you must produce</h3><div class="callout">'+esc(d.output)+'</div>'+checklist(['I completed the deliverable and can explain it aloud'],'today-output::')+'</div>';
  html+='<div class="card"><div class="section-kicker">5 · End-of-day review</div><h3>Three questions</h3>'+checklist(['What pattern / concept did I learn?','What mistake did I make?','Can I explain it without notes?'],'today-review::')+'</div></div></div>';
  html+='<div class="card next-day"><strong>Tomorrow:</strong> '+(WEEKS[0].days[(['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(currentDay())+1)%7]||WEEKS[0].days.Thu).focus+'</div>';
  document.getElementById('view').innerHTML=html;
}
function renderWeeks(){
  let html='<div class="callout">Each week is a deliberate mix of coding, system design, backend depth, project stories, and mocks. Click a week for its exact schedule.</div><h2 class="section-title">16 weeks</h2><div class="week-list">';
  WEEKS.forEach(w=>{const d=w.days[currentDay()] || w.days.Wed; const q=w.days&&Object.keys(w.days).length?progressFor('week'+w.n+'::',Object.keys(w.days)):0; html+='<div class="week" onclick="location.hash=\'week'+w.n+'\'"><div class="week-head"><div><h3>Week '+w.n+' — '+esc(w.title)+'</h3><small>'+esc(w.focus)+'</small></div><strong>'+esc(w.weekend)+'</strong></div><div class="bar"><i style="width:'+q+'%"></i></div>'+(d?'<p class="muted"><b>Today in this week:</b> '+esc(d.focus)+'</p>':'')+'</div>'; });
  document.getElementById('view').innerHTML=html+'</div>';
}
function renderWeek(n){
  const w=WEEKS[n-1]; if(!w){renderWeeks();return;} let html='<button class="back-btn" onclick="location.hash=\'weeks\'">← All weeks</button><div class="today-hero"><div><div class="eyebrow">Week '+n+'</div><h2>'+esc(w.title)+'</h2><p>'+esc(w.focus)+'</p></div><div class="time-pill">'+esc(w.weekend)+'</div></div><h2 class="section-title">Daily curriculum</h2><div class="day-list">';
  ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].forEach(day=>{const d=w.days[day]; if(d){html+='<div class="day-card"><div><b>'+day+'</b><h3>'+esc(d.focus)+'</h3><small>'+esc(d.time)+'</small><p class="muted">'+d.learn.slice(0,3).map(esc).join(' · ')+'</p></div><button onclick="location.hash=\'today\'">Open Today</button></div>'; } else { html+='<div class="day-card"><div><b>'+day+'</b><h3>Detailed material scheduled in this week</h3><small>Topic focus: '+esc(w.focus)+'</small></div></div>'; }}); html+='</div><div class="callout">For the current week, the <b>Today</b> tab contains the full study material, linked problems, external resources and end-of-day deliverable. We will keep expanding later weeks with the same level of detail.</div>'; document.getElementById('view').innerHTML=html;
}
function renderTopics(){ let html='<div class="topic-grid">'; Object.entries(TOPICS).forEach(([g,items])=>{const q=progressFor(g,items);html+='<div class="topic-card"><div class="topic-head"><h3>'+g+'</h3><span class="score">'+q+'%</span></div><p class="muted">'+items.length+' checkpoints</p>'+checklist(items,g+'::')+'</div>';}); document.getElementById('view').innerHTML=html+'</div>'; }
function renderProjects(){ const items=['Problem & requirements','Scale / metrics','Architecture diagram','My exact contribution','Key trade-offs','Failure / incident','Impact metrics','What I would redesign']; document.getElementById('view').innerHTML='<div class="two-col"><div class="card"><h3>Project Deep Dive #1</h3><p class="muted">Prepare one major production project for a 30–45 minute interviewer drill-down.</p>'+checklist(items,'project1::')+'</div><div class="card"><h3>Project Deep Dive #2</h3><p class="muted">Prepare a second project with different technical trade-offs.</p>'+checklist(items,'project2::')+'</div></div><div class="callout danger-box">Keep company-confidential architecture, code, credentials, customer data and internal URLs out of this public dashboard.</div>'; }
function renderMocks(){ const items=['Coding mock #1','Coding mock #2','System design mock #1','System design mock #2','LLD mock','Behavioral / project mock','Weekly review']; document.getElementById('view').innerHTML='<div class="grid"><div class="card"><h3>Coding</h3><p class="muted">From Week 9: 2 mocks/week, 45–60 minutes.</p></div><div class="card"><h3>System Design</h3><p class="muted">From Week 9: 2 mocks/week, 60 minutes.</p></div><div class="card"><h3>LLD</h3><p class="muted">From Week 9: 1 mock/week, 45–60 minutes.</p></div></div><div class="card"><h3>Mock log</h3>'+checklist(items,'mocks::')+'</div>'; }
function render(){ nav(); document.getElementById('pageTitle').textContent=headerTitle(); document.getElementById('todayDate').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date()); const c=(location.hash||'#dashboard').slice(1); if(c==='dashboard')renderDashboard(); else if(c==='today')renderToday(); else if(c==='weeks')renderWeeks(); else if(c==='topics')renderTopics(); else if(c==='projects')renderProjects(); else if(c==='mocks')renderMocks(); else if(c.startsWith('week'))renderWeek(Number(c.slice(4))); else renderDashboard(); }
window.addEventListener('hashchange',render);
document.getElementById('resetBtn').onclick=()=>{state={checks:{},confidence:{}};save();render();};
render();
