const PLAN={
weeks:[
['Foundations','DSA + system design fundamentals + backend scalability',['Arrays & hashing','Two pointers & sliding window','Scalability basics','Caching fundamentals','Project deep dive #1']],
['Java + MySQL/TiDB','Java concurrency, JVM, database internals',['Java collections & internals','Threads & concurrency','JVM memory & GC','MySQL indexes & EXPLAIN','Transactions & isolation','TiDB architecture']],
['Redis + Caching','Low-latency data access and distributed patterns',['Redis data structures','Cache-aside','TTL & eviction','Cache stampede','Hot keys','Rate limiting']],
['Distributed Systems','Consistency, failure and coordination',['CAP','Replication','Quorums','Idempotency','Retries & backoff','Circuit breakers']],
['Kafka I','Core Kafka architecture',['Topics & partitions','Producers','Consumer groups','Offsets','Ordering','Replication']],
['Kafka II','Reliability and production Kafka',['Delivery semantics','Retries','Dead-letter queues','Consumer lag','Rebalancing','Idempotent consumers']],
['Elasticsearch','Search architecture and scaling',['Inverted index','Mappings & analyzers','Shards & replicas','Refresh','Aggregations','Relevance']],
['CDC + Data Consistency','TiDB/MySQL → Kafka → Elasticsearch',['Transactional outbox','CDC concepts','Replay','Deduplication','Ordering','Reconciliation']],
['LLD','Clean, extensible object-oriented design',['SOLID','Composition','Interfaces','Dependency injection','Parking lot','Notification framework']],
['Concurrency','Java concurrency and production behavior',['Executors','Locks','Atomic operations','Deadlocks','Thread pools','Concurrent collections']],
['Production Engineering','Debugging, reliability and operations',['Latency debugging','CPU/memory diagnosis','DB bottlenecks','Kafka lag','Observability','Incident response']],
['Project Deep Dives','Turn real work into SDE 3 evidence',['Architecture #1','Architecture #2','Architecture #3','Trade-offs','Failures','Impact metrics']],
['Interview Mode I','Coding + system design mocks',['2 coding mocks','2 system-design mocks','1 LLD mock','Behavioral stories']],
['Interview Mode II','Weak-area correction',['Timed coding','Deep system design','Project defense','Leadership']],
['Target Company Prep','Company-specific loops and calibration',['Role research','Question patterns','Mock loop','Resume/project alignment']],
['Final Readiness','Full SDE 3 simulation',['Full loop','Final weak areas','Story refinement','Interview logistics']]
],
topics:{
'DSA':['Arrays & hashing','Two pointers','Sliding window','Binary search','Trees','Graphs','Heaps','Intervals','Monotonic stack','Backtracking','Dynamic programming'],
'Java & Spring':['Collections internals','JVM memory','GC','Java Memory Model','Threads','Executors','CompletableFuture','Locks & atomics','Spring DI','Transactions','Connection/thread pools'],
'MySQL & TiDB':['Indexes','EXPLAIN','Query optimization','Transactions','Isolation levels','Locks & deadlocks','MVCC','Replication','Partitioning','Sharding','TiDB architecture'],
'Redis':['Strings/Hash/Set/ZSet','Cache-aside','TTL','Eviction','Cache stampede','Hot keys','Rate limiting','Distributed locks','Streams'],
'Kafka':['Topics','Partitions','Producers','Consumer groups','Offsets','Ordering','Replication','Delivery semantics','Retries','DLQ','Consumer lag','Idempotency'],
'Elasticsearch':['Inverted index','Mappings','Analyzers','Queries','Aggregations','Shards','Replicas','Refresh','Reindexing','Scaling'],
'Aerospike':['Data model','Namespaces','Sets','Records','Bins','Partitions','Replication','Consistency','TTL','Rebalancing','When to choose it'],
'LLD & Concurrency':['SOLID','Composition','Interfaces','DI','Design patterns','Parking lot','Scheduler','Rate limiter','Thread safety','Deadlocks'],
'System Design':['Requirements','Estimation','APIs','Data model','Caching','Queues','Partitioning','Consistency','Reliability','Observability','Cost','Failure modes'],
'Leadership & Behavioral':['Ownership','Conflict','Influence','Mentoring','Failure','Ambiguity','Technical decision','Incident','Cost/performance win','Cross-team work']
},
weekDetails:[
{title:'Week 1 — Foundations',hours:'~17h',weekday:'Mon 1h DSA · Tue 1h15 system design · Wed 1h DSA · Thu 1h15 backend · Fri 45m project',weekend:'Sat ~6h · Sun ~6h',tasks:['DSA: Arrays + hashing','System design: scalability, load balancing, caching, sync vs async','DSA: two pointers + sliding window','Backend: rate limiting, timeouts, retries','Project deep dive #1','Saturday: URL shortener design + LLD parking lot','Sunday: rate limiter design + coding mock + 2 behavioral stories']},
{title:'Week 2 — Java + MySQL/TiDB',hours:'~17h',weekday:'Java collections, concurrency, JVM, indexes, EXPLAIN, transactions',weekend:'Deep Java concurrency + MySQL/TiDB architecture',tasks:['Java Collections internals','Threads & concurrency','JVM memory + GC','MySQL indexes + EXPLAIN','Transactions + isolation','TiDB architecture','Design exercise: service backed by TiDB + cache']},
{title:'Week 3 — Redis + Caching',hours:'~17h',weekday:'Redis fundamentals + caching patterns',weekend:'Cache-heavy system designs',tasks:['Redis data structures','Cache-aside','TTL and eviction','Cache stampede','Hot keys','Rate limiting','Distributed locks and streams','Design: high-scale product catalog with Redis']},
{title:'Week 4 — Distributed Systems',hours:'~17h',weekday:'Consistency + failure handling',weekend:'Distributed systems design drills',tasks:['CAP','Replication','Quorums','Idempotency','Retries and backoff','Circuit breakers','Failure modes and graceful degradation']},
{title:'Week 5 — Kafka I',hours:'~17h',weekday:'Kafka architecture',weekend:'Producer/consumer deep dive',tasks:['Topics and partitions','Producers','Consumer groups','Offsets','Ordering','Replication','Partition-key selection']},
{title:'Week 6 — Kafka II',hours:'~17h',weekday:'Production Kafka',weekend:'Failure and delivery semantics',tasks:['At-most-once','At-least-once','Idempotent consumers','Retries','DLQ','Consumer lag','Rebalancing','Poison messages']},
{title:'Week 7 — Elasticsearch',hours:'~16h',weekday:'Search internals',weekend:'Search architecture',tasks:['Inverted index','Mappings','Analyzers','Queries','Aggregations','Shards and replicas','Refresh','Reindexing','Scaling']},
{title:'Week 8 — CDC + Data Consistency',hours:'~17h',weekday:'MySQL/TiDB → Kafka → Elasticsearch',weekend:'Consistency and recovery design',tasks:['Transactional outbox','CDC concepts','Replay','Deduplication','Ordering','Reconciliation','Failure between DB and search']},
{title:'Week 9 — LLD',hours:'~17h',weekday:'SOLID + clean design',weekend:'LLD mock problems',tasks:['SOLID','Composition','Interfaces','Dependency injection','Parking lot','Notification framework','Scheduler','Rate limiter']},
{title:'Week 10 — Concurrency',hours:'~17h',weekday:'Java concurrency',weekend:'Concurrency coding + diagnosis',tasks:['Executors','Locks','Atomic operations','Deadlocks','Thread pools','Concurrent collections','Thread-safety reasoning']},
{title:'Week 11 — Production Engineering',hours:'~17h',weekday:'Debugging + observability',weekend:'Production incident simulations',tasks:['Latency debugging','CPU/memory diagnosis','DB bottlenecks','Kafka lag','Logs/metrics/traces','Incident response','Mitigation → root cause → prevention']},
{title:'Week 12 — Project Deep Dives',hours:'~16h',weekday:'Document 3 major projects',weekend:'Project defense simulations',tasks:['Problem','Scale / metrics','Architecture','Exact ownership','Trade-offs','Failures','Impact','Redesign']},
{title:'Week 13 — Interview Mode I',hours:'~16h',weekday:'Timed DSA + design',weekend:'Mocks',tasks:['2 coding mocks','2 system-design mocks','1 LLD mock','Behavioral stories','Mistake log']},
{title:'Week 14 — Interview Mode II',hours:'~16h',weekday:'Weak-area correction',weekend:'Targeted mocks',tasks:['Timed coding','Deep system design','Project defense','Leadership','Production debugging']},
{title:'Week 15 — Target Company Prep',hours:'~14h',weekday:'Company-specific preparation',weekend:'Mock loop',tasks:['Role research','Question patterns','Mock loop','Resume/project alignment','Company-specific behavioral calibration']},
{title:'Week 16 — Final Readiness',hours:'~14h',weekday:'Revision',weekend:'Full SDE 3 simulation',tasks:['Full loop','Final weak areas','Story refinement','Interview logistics','Final system-design drills']}
]
};

const KEY='sde3-prep-state-v2';
let state={checks:{},confidence:{},problems:0,mocks:0,notes:''};
try{state=Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function done(id){return !!state.checks[id];}
function toggle(id){state.checks[id]=!state.checks[id];save();render();}
function confidence(id){return state.confidence[id]||0;}
function setConfidence(id,v){state.confidence[id]=Number(v);save();render();}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function percent(arr,prefix){if(!arr.length)return 0;return Math.round(arr.filter(x=>done(prefix+x)).length/arr.length*100);}
function allChecks(){const out=[];Object.keys(PLAN.topics).forEach(g=>PLAN.topics[g].forEach(x=>out.push(g+'::'+x)));PLAN.weeks.forEach((w,i)=>w[2].forEach(x=>out.push('W'+(i+1)+'::'+x)));return out;}
function overall(){const a=allChecks();return Math.round(a.filter(done).length/a.length*100);}
function card(html,cls='card'){return '<div class="'+cls+'">'+html+'</div>';}
function checklist(items,prefix){return '<div class="checklist">'+items.map((x,i)=>{const id=prefix+x;return '<label><input type="checkbox" '+(done(id)?'checked':'')+' onchange="toggle(\''+esc(id).replace(/'/g,"\\'")+'\')"><span>'+ (done(id)?'<s>':'')+esc(x)+(done(id)?'</s>':'')+'</span></label>';}).join('')+'</div>';}
function nav(){const items=[['dashboard','Dashboard'],['today','Today'],['weeks','16-Week Plan'],['topics','Topics & Checklists'],['projects','Projects'],['mocks','Mock Interviews']];const el=document.getElementById('nav');el.innerHTML=items.map(x=>'<button class="nav-btn '+((location.hash||'#dashboard').slice(1)===x[0]?'active':'')+'" onclick="location.hash=\''+x[0]+'\'">'+x[1]+'</button>').join('');}
function renderDashboard(){const p=overall();let html='<div class="hero"><div><div class="eyebrow">Current target</div><h2>SDE 2 → SDE 3 Backend Engineer</h2><p>16-week preparation plan built around your full-time office schedule, with the heavy work on weekends.</p><div class="callout" style="margin-top:18px"><strong>Your stack:</strong> Java · Spring Boot · MySQL · TiDB/Rigel · Elasticsearch · Redis · Kafka · Aerospike</div></div><div class="progress-ring"><div class="ring" style="--p:'+p*3.6+'deg"><span>'+p+'%</span></div></div></div>';
html+='<div class="stats grid"><div class="card"><div class="muted">Overall readiness</div><div class="metric">'+p+'%</div></div><div class="card"><div class="muted">DSA target</div><div class="metric">180–200</div><div class="small">quality problems</div></div><div class="card"><div class="muted">Weekly target</div><div class="metric">17h</div><div class="small">~5h weekdays + 12h weekend</div></div></div>';
html+='<h2 class="section-title">What matters most for SDE 3</h2><div class="grid">';[['System Design','Requirements, estimation, architecture, bottlenecks, reliability, cost'],['Distributed Backend','Kafka, Redis, databases, consistency, idempotency, failures'],['Java + Spring','Concurrency, JVM, transactions, pools, production behavior'],['DSA','Patterns and clean implementation; not endless grinding'],['LLD','SOLID, composition, extensibility, concurrency'],['Leadership','Ownership, influence, mentoring, incidents, technical judgment']].forEach(x=>html+=card('<h3>'+x[0]+'</h3><p class="muted">'+x[1]+'</p>'));html+='</div>';
html+='<h2 class="section-title">This week — Week 1: Foundations</h2>'+card('<strong>Goal:</strong> establish DSA patterns + system-design fundamentals + backend scalability.<p class="muted">Weekdays stay light around office. Saturday and Sunday carry the deep work.</p>'+checklist(PLAN.weekDetails[0].tasks,'week0::'));
html+='<h2 class="section-title">Core skill progress</h2><div class="topic-grid">';Object.entries(PLAN.topics).forEach(([g,items])=>{const q=percent(items,g+'::');html+='<div class="topic-card"><div class="topic-head"><h3>'+g+'</h3><span class="score">'+q+'%</span></div><div class="bar"><i style="width:'+q+'%"></i></div></div>';});html+='</div>';return html;}
function todayTasks(){const d=new Date().getDay();if(d===6)return ['2–3 DSA problems','System-design deep work','LLD practice: Parking Lot','Review mistakes'];if(d===0)return ['DSA mock','System-design mock','Behavioral story','Weekly review'];if(d===5)return ['Light revision','Project / behavioral story'];return ['DSA practice: Arrays + hashing','System-design: scalability + caching','Backend: timeouts + retries'];}
function renderToday(){const tasks=todayTasks();return '<div class="hero"><div><div class="eyebrow">Today</div><h2>'+new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date())+'</h2><p>Target around your office schedule. Keep tonight focused and specific.</p></div><div class="callout"><strong>Rule:</strong> weekdays = 60–75 min. Save 5–7 hour deep-work blocks for Saturday and Sunday.</div></div>'+card('<h3>Today’s checklist</h3>'+checklist(tasks,'today::'))+ '<h2 class="section-title">Week 1 detailed schedule</h2>'+card('<div class="schedule"><div><strong>Monday</strong><span>60 min · DSA — Arrays + Hashing</span></div><div><strong>Tuesday</strong><span>75 min · System Design — scalability, load balancing, caching, sync vs async</span></div><div><strong>Wednesday</strong><span>60 min · DSA — two pointers + sliding window</span></div><div><strong>Thursday</strong><span>75 min · Backend — rate limiting, timeouts, retries</span></div><div><strong>Friday</strong><span>45 min · Project deep dive #1</span></div><div><strong>Saturday</strong><span>~6h · DSA + URL shortener design + LLD parking lot</span></div><div><strong>Sunday</strong><span>~6h · DSA + rate limiter design + coding mock + behavioral stories</span></div></div>');}
function renderWeeks(){let html='<div class="callout">16 weeks · ~17h/week · weekdays deliberately light · weekends deliberately heavy.</div><h2 class="section-title">16-week roadmap</h2><div class="week-list">';PLAN.weeks.forEach((w,i)=>{const p=percent(w[2],'W'+(i+1)+'::');html+='<div class="week" onclick="location.hash=\'week'+(i+1)+'\'"><div class="week-head"><div><h3>Week '+(i+1)+' — '+w[0]+'</h3><small>'+w[1]+'</small></div><strong>'+p+'%</strong></div><div class="bar"><i style="width:'+p+'%"></i></div></div>';});return html+'</div>';}
function renderWeek(n){const d=PLAN.weekDetails[n-1],w=PLAN.weeks[n-1],p=percent(w[2],'W'+n+'::');return '<div class="hero"><div><div class="eyebrow">Week '+n+'</div><h2>'+d.title+'</h2><p>'+w[1]+'</p></div><div class="progress-ring"><div class="ring" style="--p:'+p*3.6+'deg"><span>'+p+'%</span></div></div></div><div class="grid"><div class="card"><div class="muted">Time target</div><div class="metric">'+d.hours+'</div></div><div class="card"><h3>Weekdays</h3><p class="muted">'+d.weekday+'</p></div><div class="card"><h3>Weekend</h3><p class="muted">'+d.weekend+'</p></div></div>'+card('<h3>Checklist</h3>'+checklist(w[2],'W'+n+'::'))+'<h2 class="section-title">What good looks like</h2>'+card('<p class="muted">You should be able to explain the concepts from first principles, connect them to a real backend architecture, discuss scale and failure modes, and defend your trade-offs without relying on memorized diagrams.');}
function renderTopics(){let html='<div class="topic-grid">';Object.entries(PLAN.topics).forEach(([g,items])=>{const p=percent(items,g+'::');html+='<div class="topic-card"><div class="topic-head"><h3>'+g+'</h3><span class="score">'+p+'%</span></div><p class="muted">Rate your confidence after checking an item.</p>'+checklist(items,g+'::')+'<div class="confidence">Confidence: <select onchange="setConfidence(\''+esc(g)+'\',this.value)"><option value="0">Not rated</option><option value="1">1 — Don’t know</option><option value="2">2 — Familiar</option><option value="3">3 — Can explain</option><option value="4">4 — Can implement</option><option value="5">5 — Interview ready</option></select></div></div>';});return html+'</div>';}
function renderProjects(){return '<div class="two-col">'+card('<h3>Project Deep Dive #1</h3><p class="muted">Prepare one major production project for a 30–45 minute interviewer drill-down.</p>'+checklist(['Problem & requirements','Scale / metrics','Architecture diagram','My exact contribution','Key trade-offs','Failure / incident','Impact metrics','What I would redesign'],'proj1::'))+card('<h3>Project Deep Dive #2</h3><p class="muted">Prepare a second project with comparable depth.</p>'+checklist(['Problem & requirements','Scale / metrics','Architecture diagram','My exact contribution','Key trade-offs','Failure / incident','Impact metrics','What I would redesign'],'proj2::'))+'</div><div class="two-col" style="margin-top:18px">'+card('<h3>Interview story formula</h3><p class="muted">Situation → problem → constraints → options → decision → action → result → lesson.</p>')+card('<h3>Confidentiality</h3><p class="muted">Keep company names, internal URLs, credentials, proprietary code and customer data out of this public site. Use abstracted descriptions.</p>')+'</div>';}
function renderMocks(){return '<div class="grid">'+card('<h3>Coding mocks</h3><p class="muted">From Week 13: 2/week · 45–60 min.</p>')+card('<h3>System design mocks</h3><p class="muted">From Week 13: 2/week · 60 min.</p>')+card('<h3>LLD mock</h3><p class="muted">From Week 13: 1/week · 45–60 min.</p>')+'</div>'+card('<h3>Mock log</h3>'+checklist(['Coding mock #1','Coding mock #2','System design mock #1','System design mock #2','LLD mock','Behavioral/project mock','Weekly review'],'mock::'));}
function render(){nav();const hash=(location.hash||'#dashboard').slice(1);let content=hash==='dashboard'?renderDashboard():hash==='today'?renderToday():hash==='weeks'?renderWeeks():hash==='topics'?renderTopics():hash==='projects'?renderProjects():hash==='mocks'?renderMocks():/^week\d+$/.test(hash)?renderWeek(Number(hash.slice(4))):renderDashboard();document.getElementById('view').innerHTML=content;document.getElementById('pageTitle').textContent=hash==='dashboard'?'Dashboard':hash==='today'?'Today':hash==='weeks'?'16-Week Plan':hash==='topics'?'Topics & Checklists':hash==='projects'?'Projects':hash==='mocks'?'Mock Interviews':/^week\d+$/.test(hash)?'Week '+hash.slice(4):'Dashboard';document.getElementById('todayDate').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date());}
window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',render);if(document.readyState!=='loading')render();
