(()=>{
  const START=new Date('2026-08-17T00:00:00+05:30');
  const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
  const KEY='sde3-coach-v1';
  let state={readiness:{},mistakes:[],mocks:[]};
  try{state=Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){}
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const route=()=>location.hash.slice(1)||'dashboard';
  const currentWeek=()=>Math.max(1,Math.min(16,Math.floor((Date.now()-START.getTime())/(7*86400000))+1));
  const currentDay=()=>{const d=new Date().getDay();return d===0?'Sun':DAYS[d-1]};
  const readAreas=['DSA','System Design / HLD','Java + Spring','MySQL / TiDB','Kafka','Redis','Elasticsearch','Aerospike','LLD / Concurrency','Production Engineering','Project Deep Dive','Leadership / Behavioral'];
  function setScore(a,v){state.readiness[a]=+v;save();renderCoach();}
  function removeMistake(i){state.mistakes.splice(i,1);save();renderCoach();}
  function addMistake(){const t=document.getElementById('mistakeText');const a=document.getElementById('mistakeArea');if(!t||!t.value.trim())return;state.mistakes.unshift({date:new Date().toISOString().slice(0,10),area:a.value,text:t.value.trim(),fix:''});save();renderCoach();}
  function updateMistake(i,field,val){state.mistakes[i][field]=val;save();}
  function addMock(){state.mocks.unshift({date:new Date().toISOString().slice(0,10),type:'System Design',company:'Core',scores:{Coding:0,Communication:0,Depth:0,Tradeoffs:0,Leadership:0},notes:''});save();renderCoach();}
  function updMock(i,field,val){state.mocks[i].scores[field]=+val;save();}
  function delMock(i){state.mocks.splice(i,1);save();renderCoach();}
  function coachNav(){
    const extra=[['readiness','Readiness'],['mistakes','Mistake Bank'],['scorecards','Mock Scorecards']];
    const nav=document.getElementById('nav');
    if(!nav)return;
    const base=[['dashboard','Dashboard'],['today','Today'],['weeks','16-Week Plan'],['topics','Topics & Checklists'],['company-questions','Company Questions'],['companies','Company Targets'],['projects','Projects'],['mocks','Mock Interviews']];
    nav.innerHTML=base.concat(extra).map(x=>`<button class="nav-btn ${route()===x[0]?'active':''}" onclick="location.hash='${x[0]}'">${x[1]}</button>`).join('');
  }
  function injectStyle(){if(document.getElementById('coach-style'))return;const s=document.createElement('style');s.id='coach-style';s.textContent=`
  .coach-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.coach-card{background:#fff;border:1px solid #e4e8ef;border-radius:14px;padding:18px}.coach-card h3{margin:0 0 8px}.score-row{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:9px 0}.score-row input{width:120px}.score-badge{font-size:13px;font-weight:800}.mistake{border:1px solid #e4e8ef;border-radius:12px;padding:14px;margin:10px 0;background:#fff}.mistake textarea{width:100%;min-height:70px;box-sizing:border-box;margin-top:6px;border:1px solid #dbe1ea;border-radius:8px;padding:8px;font:inherit}.coach-actions{display:flex;gap:8px;flex-wrap:wrap}.coach-btn{border:1px solid #dbe1ea;background:#fff;border-radius:8px;padding:8px 11px;cursor:pointer}.coach-btn.primary{background:#0b1020;color:#fff}.mock-table{width:100%;border-collapse:collapse}.mock-table th,.mock-table td{padding:9px;border-bottom:1px solid #eef0f4;text-align:left;font-size:12px;vertical-align:top}.mock-table select,.mock-table input,.mock-table textarea{width:100%;box-sizing:border-box;padding:6px;border:1px solid #dbe1ea;border-radius:7px}.mock-table textarea{min-height:60px}.gate{border-left:4px solid #0b1020;background:#f8fafc;padding:12px 14px;margin:10px 0}.muted2{color:#667085;font-size:12px}.full{grid-column:1/-1}@media(max-width:1000px){.coach-grid{grid-template-columns:1fr 1fr}}@media(max-width:700px){.coach-grid{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}
  function readiness(){const vals=readAreas.map(a=>state.readiness[a]||0);const avg=vals.reduce((a,b)=>a+b,0)/(vals.length||1);return Math.round(avg*20);}
  function renderReadiness(){injectStyle();const overall=readiness();let html=`<div class="hero"><div><div class="eyebrow">Interview readiness</div><h2>Are you actually ready for SDE 3?</h2><p>Rate each area from 1–5 based on what you can demonstrate in an interview, not how much material you have consumed.</p></div><div class="ring-wrap"><div class="ring" style="--p:${overall*3.6}deg"><span>${overall}%</span></div></div></div><h2 class="section-title">Readiness by competency</h2><div class="coach-grid">`;
    readAreas.forEach(a=>{const v=state.readiness[a]||0;html+=`<div class="coach-card"><h3>${esc(a)}</h3><div class="score-row"><span class="muted2">1 = weak · 5 = interview-ready</span><span class="score-badge">${v}/5</span></div><input type="range" min="0" max="5" step="1" value="${v}" onchange="window.__coachSet('${esc(a).replace(/'/g,"\\'")}',this.value)"><div class="bar"><i style="width:${v*20}%"></i></div></div>`});
    html+=`</div><h2 class="section-title">Weekly gate</h2><div class="callout">Do not move to the next week just because the calendar says so. Move when your weakest active competency is at least <strong>3/5</strong> and you can complete the week's core deliverable without looking at a solution.</div><div class="gate"><strong>Current week:</strong> Week ${currentWeek()} · ${currentDay()}<br><span class="muted2">Use the Today tab for the exact study material. Use this page at the end of the week.</span></div>`;return html}
  function renderMistakes(){injectStyle();let html=`<div class="hero"><div><div class="eyebrow">Mistake Bank</div><h2>Turn failures into revision material</h2><p>Every failed problem, weak design decision or interview mistake should become a reusable lesson.</p></div><div class="stack">Rule: don't delete a mistake until you can explain how you'll avoid it next time.</div></div><div class="coach-card" style="margin-top:16px"><div class="coach-actions"><select id="mistakeArea">${readAreas.map(a=>`<option>${esc(a)}</option>`).join('')}</select><input id="mistakeText" style="flex:1;min-width:240px;padding:9px;border:1px solid #dbe1ea;border-radius:8px" placeholder="What went wrong?"><button class="coach-btn primary" onclick="window.__coachAddMistake()">Add mistake</button></div></div>`;
    html+='<h2 class="section-title">Open mistakes</h2>'; if(!state.mistakes.length) html+='<div class="callout">No mistakes recorded yet. This is empty only because you have not started logging them.</div>';state.mistakes.forEach((m,i)=>{html+=`<div class="mistake"><div class="study-head"><strong>${esc(m.area)}</strong><span class="daytag">${esc(m.date)}</span></div><div class="muted2">Mistake</div><textarea oninput="window.__coachMistake(${i},'text',this.value)">${esc(m.text)}</textarea><div class="muted2" style="margin-top:8px">Fix / mental model</div><textarea oninput="window.__coachMistake(${i},'fix',this.value)">${esc(m.fix||'')}</textarea><div class="coach-actions" style="margin-top:8px"><button class="coach-btn" onclick="window.__coachDelMistake(${i})">Delete</button></div></div>`});return html;}
  function renderScorecards(){injectStyle();let html=`<div class="hero"><div><div class="eyebrow">Mock scorecards</div><h2>Measure interview performance</h2><p>Completion alone doesn't matter. Track how you perform under interview conditions.</p></div><div class="stack">Target by Week 13–16: consistently 4/5+ across technical depth, communication and trade-offs.</div></div><div class="coach-actions" style="margin:16px 0"><button class="coach-btn primary" onclick="window.__coachAddMock()">+ Add mock</button></div><div class="coach-card"><table class="mock-table"><thead><tr><th>Date</th><th>Type</th><th>Company</th><th>Scores</th><th>Notes</th><th></th></tr></thead><tbody>`;
    state.mocks.forEach((m,i)=>{html+=`<tr><td>${esc(m.date)}</td><td><select onchange="window.__coachMock(${i},'type',this.value)"><option ${m.type==='Coding'?'selected':''}>Coding</option><option ${m.type==='System Design'?'selected':''}>System Design</option><option ${m.type==='LLD'?'selected':''}>LLD</option><option ${m.type==='Behavioral'?'selected':''}>Behavioral</option></select></td><td><input value="${esc(m.company||'')}" onchange="window.__coachMock(${i},'company',this.value)"></td><td>${Object.keys(m.scores).map(k=>`${esc(k)} <select onchange="window.__coachMockScore(${i},'${esc(k)}',this.value)"><option value="0" ${m.scores[k]===0?'selected':''}>-</option><option value="1" ${m.scores[k]===1?'selected':''}>1</option><option value="2" ${m.scores[k]===2?'selected':''}>2</option><option value="3" ${m.scores[k]===3?'selected':''}>3</option><option value="4" ${m.scores[k]===4?'selected':''}>4</option><option value="5" ${m.scores[k]===5?'selected':''}>5</option></select>`).join('<br>')}</td><td><textarea onchange="window.__coachMock(${i},'notes',this.value)">${esc(m.notes||'')}</textarea></td><td><button class="coach-btn" onclick="window.__coachDelMock(${i})">Delete</button></td></tr>`});
    html+='</tbody></table></div>';return html;}
  function renderCoach(){const r=route();const v=document.getElementById('view');if(!v)return;coachNav();if(r==='readiness'){document.getElementById('pageTitle').textContent='Readiness';v.innerHTML=renderReadiness();return}if(r==='mistakes'){document.getElementById('pageTitle').textContent='Mistake Bank';v.innerHTML=renderMistakes();return}if(r==='scorecards'){document.getElementById('pageTitle').textContent='Mock Scorecards';v.innerHTML=renderScorecards();return}}
  window.__coachSet=setScore;window.__coachAddMistake=addMistake;window.__coachDelMistake=removeMistake;window.__coachMistake=updateMistake;window.__coachAddMock=addMock;window.__coachDelMock=delMock;
  window.__coachMock=(i,f,v)=>{state.mocks[i][f]=v;save();};window.__coachMockScore=(i,f,v)=>{state.mocks[i].scores[f]=+v;save();};
  window.addEventListener('hashchange',()=>setTimeout(renderCoach,0));
  window.addEventListener('load',()=>setTimeout(()=>{try{const oldWeek=window.currentWeek;window.currentWeek=()=>{const q=new URLSearchParams(location.search).get('week');if(q&&+q>=1&&+q<=16)return window.weeks?window.weeks[+q-1]:oldWeek();const n=Math.floor((Date.now()-START.getTime())/(7*86400000))+1;return window.weeks?window.weeks[Math.max(0,Math.min(15,n-1))]:oldWeek();};}catch(e){} renderCoach();},100));
})();
