(()=>{
const START=new Date('2026-08-17T00:00:00+05:30');
const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const KEY='sde3-v4';
let s={calendar:{},backupVersion:1};
try{s=Object.assign(s,JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){}
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const iso=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const dayIdx=d=>{const n=d.getDay();return n===0?6:n-1};
const weekNo=()=>Math.max(1,Math.min(16,Math.floor((Date.now()-START.getTime())/604800000)+1));
const dateFor=(w,i)=>new Date(START.getTime()+((w-1)*7+i)*86400000);
function planFor(w,i){try{const d=weeks[w-1].days[DAYS[i]];return d||null;}catch(e){return null}}
function ensureDay(date,w,i){const k=iso(date);if(!s.calendar[k])s.calendar[k]={status:'',minutes:0,note:'',week:w,day:DAYS[i]};return s.calendar[k]}
function classify(day){const d=new Date(day+'T23:59:59+05:30');const today=new Date();const same=day===iso(today);if(s.calendar[day]?.status) return s.calendar[day].status;if(d<today && !same)return 'skipped';return same?'in-progress':'upcoming'}
function minutesPlanned(w,i){const d=planFor(w,i);if(!d)return 0;const m=String(d.time).match(/(\d+)\s*min/);if(m)return +m[1];if(String(d.time).includes('5–7h'))return 360;return 60}
function weekSummary(w){const now=new Date();const currentStart=new Date(START.getTime()+(w-1)*7*86400000);let planned=0,logged=0,completed=0,partial=0,skipped=0,done=[];for(let i=0;i<7;i++){const dt=dateFor(w,i);if(dt>now)continue;planned+=minutesPlanned(w,i);const k=iso(dt),c=s.calendar[k];const st=classify(k);if(c?.minutes)logged+=+c.minutes;if(st==='completed'){completed++;done.push({day:DAYS[i],topic:planFor(w,i)?.focus||''})}else if(st==='partial')partial++;else if(st==='skipped')skipped++;}return{planned,logged,completed,partial,skipped,done}}
function fmt(m){const h=Math.floor(m/60),mm=m%60;return h+(mm?'h '+mm+'m':'h')}
function style(){if(document.getElementById('ux-style'))return;const st=document.createElement('style');st.id='ux-style';st.textContent=`
.top-actions{display:flex;align-items:center;justify-content:flex-end;gap:9px;flex-wrap:wrap;max-width:520px}.quick-link{display:inline-flex;align-items:center;white-space:nowrap;text-decoration:none!important;background:#fff;border:1px solid #dbe1ea;border-radius:9px;padding:8px 11px;color:#344054!important;font-size:12px;font-weight:600}.quick-link:hover{background:#f8fafc}.summary-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:16px 0}.summary-stat{background:#fff;border:1px solid #e4e8ef;border-radius:12px;padding:14px}.summary-stat span{display:block;color:#667085;font-size:11px}.summary-stat b{display:block;font-size:20px;margin:5px 0}.calendar-table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e4e8ef;border-radius:12px;overflow:hidden}.calendar-table th,.calendar-table td{padding:11px;border-bottom:1px solid #eef0f4;text-align:left;font-size:12px;vertical-align:top}.calendar-table th{background:#f8fafc;color:#667085;text-transform:uppercase;font-size:10px;letter-spacing:.06em}.status-pill{display:inline-block;border-radius:999px;padding:4px 8px;font-size:10px;font-weight:700}.status-completed{background:#ecfdf3;color:#027a48}.status-partial{background:#fffaeb;color:#b54708}.status-skipped{background:#fef3f2;color:#b42318}.status-in-progress{background:#eef4ff;color:#175cd3}.status-upcoming{background:#f2f4f7;color:#667085}.calendar-actions{display:flex;gap:6px;flex-wrap:wrap}.mini-btn{border:1px solid #dbe1ea;background:#fff;border-radius:7px;padding:6px 8px;font-size:11px;cursor:pointer}.mini-btn.active{background:#0b1020;color:#fff}.backup-row{display:flex;gap:10px;flex-wrap:wrap}.file-btn{display:inline-flex;align-items:center;gap:6px;padding:9px 12px;border:1px solid #dbe1ea;border-radius:8px;background:#fff;cursor:pointer;font-size:12px}.coach-card + .coach-card{margin-top:14px}.summary-done{margin:0;padding-left:20px}.summary-done li{padding:3px 0}@media(max-width:1100px){.summary-grid{grid-template-columns:repeat(3,1fr)}.top-actions{max-width:420px}}@media(max-width:700px){.summary-grid{grid-template-columns:1fr 1fr}.top-actions{justify-content:flex-start}.calendar-table{min-width:850px}.calendar-wrap{overflow:auto}}
`;document.head.appendChild(st)}
function navPatch(){const nav=document.getElementById('nav');if(!nav)return;const buttons=[...nav.querySelectorAll('button')];const exists=t=>buttons.some(b=>b.textContent.trim()===t);let add=[];if(!exists('Week Summary'))add.push(['week-summary','Week Summary']);if(!exists('Progress Backup'))add.push(['backup','Progress Backup']);if(add.length){nav.innerHTML+=add.map(x=>`<button class="nav-btn" onclick="location.hash='${x[0]}'">${x[1]}</button>`).join('')}}
function topLinksPatch(){const t=document.querySelector('.top-actions');if(!t)return;let need=[];if(!t.querySelector('[data-ux="summary"]'))need.push('<a data-ux="summary" class="quick-link" href="#week-summary">Week summary</a>');if(!t.querySelector('[data-ux="backup"]'))need.push('<a data-ux="backup" class="quick-link" href="#backup">Progress backup</a>');t.insertAdjacentHTML('afterbegin',need.join(''))}
function saveDay(day,status){const [y,m,d]=day.split('-').map(Number);const dt=new Date(y,m-1,d);const w=Math.floor((dt-START)/604800000)+1;const i=dayIdx(dt);const c=ensureDay(dt,w,i);c.status=status;save();renderPage()}
function editMinutes(day){const current=s.calendar[day]?.minutes||0;const v=prompt('Actual minutes studied for '+day+':',String(current));if(v===null)return;const n=Math.max(0,Math.round(Number(v)));const c=s.calendar[day]||{status:'',note:'',week:1,day:''};c.minutes=n;s.calendar[day]=c;save();renderPage()}
function editNote(day){const v=prompt('What did you accomplish?',s.calendar[day]?.note||'');if(v===null)return;const c=s.calendar[day]||{status:'',minutes:0,week:1,day:''};c.note=v;s.calendar[day]=c;save();renderPage()}
function renderSummary(){style();const w=weekNo(),sum=weekSummary(w);let rows='';for(let i=0;i<7;i++){const dt=dateFor(w,i),k=iso(dt),d=planFor(w,i),st=classify(k),c=s.calendar[k]||{};rows+=`<tr><td><strong>${DAYS[i]}</strong><div class="muted2">${k}</div></td><td>${esc(d?.focus||'—')}</td><td>${fmt(minutesPlanned(w,i))}</td><td>${c.minutes?fmt(c.minutes):'—'}</td><td><span class="status-pill status-${st}">${st}</span></td><td>${esc(c.note||'—')}</td><td><div class="calendar-actions"><button class="mini-btn ${st==='completed'?'active':''}" onclick="window.__uxDay('${k}','completed')">Done</button><button class="mini-btn ${st==='partial'?'active':''}" onclick="window.__uxDay('${k}','partial')">Partial</button><button class="mini-btn ${st==='skipped'?'active':''}" onclick="window.__uxDay('${k}','skipped')">Skip</button><button class="mini-btn" onclick="window.__uxMinutes('${k}')">Hours</button><button class="mini-btn" onclick="window.__uxNote('${k}')">Note</button></div></td></tr>`}
return `<div class="hero"><div><div class="eyebrow">Weekly accountability</div><h2>Week ${w} summary</h2><p>Calendar-driven tracking. Past days without a manual update are automatically counted as skipped.</p></div><div class="stack">This is the accountability layer — not the curriculum itself.</div></div><div class="summary-grid"><div class="summary-stat"><span>Planned</span><b>${fmt(sum.planned)}</b></div><div class="summary-stat"><span>Logged</span><b>${fmt(sum.logged)}</b></div><div class="summary-stat"><span>Completed</span><b>${sum.completed} days</b></div><div class="summary-stat"><span>Partial</span><b>${sum.partial} days</b></div><div class="summary-stat"><span>Skipped</span><b>${sum.skipped} days</b></div></div><div class="coach-card"><h3>What you actually did</h3>${sum.done.length?'<ul class="summary-done">'+sum.done.map(x=>'<li><strong>'+esc(x.day)+'</strong> — '+esc(x.topic)+'</li>').join('')+'</ul>':'<p class="muted2">Nothing marked completed yet.</p>'}</div><h2 class="section-title">Calendar</h2><div class="calendar-wrap"><table class="calendar-table"><thead><tr><th>Day</th><th>Planned study</th><th>Planned</th><th>Logged</th><th>Status</th><th>Note</th><th>Update</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderBackup(){style();const payload={version:2,exportedAt:new Date().toISOString(),calendar:s.calendar,readiness:JSON.parse(localStorage.getItem('sde3-coach-v1')||'{}'),legacy:JSON.parse(localStorage.getItem('sde3-v3')||'{}')};return `<div class="hero"><div><div class="eyebrow">Progress backup</div><h2>Take your preparation state with you</h2><p>Your curriculum lives in GitHub; this file backs up your private progress, calendar, readiness, mistakes and mocks.</p></div><div class="stack">Export regularly. Import on another browser/device.</div></div><div class="coach-card" style="margin-top:16px"><h3>Backup / Restore</h3><p class="muted2">This is a safe client-side backup. It does not expose a GitHub token or credentials.</p><div class="backup-row"><button class="file-btn" onclick="window.__uxExport()">Export progress JSON</button><label class="file-btn">Import progress JSON<input id="uxImport" type="file" accept="application/json" style="display:none"></label></div></div><div class="callout" style="margin-top:16px"><strong>Current limitation:</strong> the published GitHub Pages site still cannot securely write private progress directly into your GitHub repository. This backup solves portability without putting credentials into the website.</div>`}
function exportData(){const payload={version:2,exportedAt:new Date().toISOString(),calendar:s.calendar,coach:JSON.parse(localStorage.getItem('sde3-coach-v1')||'{}'),legacy:JSON.parse(localStorage.getItem('sde3-v3')||'{}')};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sde3-progress-'+iso(new Date())+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(file){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(p.calendar)s.calendar=p.calendar;if(p.coach)localStorage.setItem('sde3-coach-v1',JSON.stringify(p.coach));if(p.legacy)localStorage.setItem('sde3-v3',JSON.stringify(p.legacy));save();renderPage();alert('Progress restored.')}catch(e){alert('Invalid backup file.')}};r.readAsText(file)}
function renderPage(){const r=location.hash.slice(1);navPatch();topLinksPatch();if(r==='week-summary'){document.getElementById('pageTitle').textContent='Week Summary';document.getElementById('view').innerHTML=renderSummary();return}if(r==='backup'){document.getElementById('pageTitle').textContent='Progress Backup';document.getElementById('view').innerHTML=renderBackup();const inp=document.getElementById('uxImport');if(inp)inp.onchange=e=>{if(e.target.files[0])importData(e.target.files[0])};return}}
window.__uxDay=saveDay;window.__uxMinutes=editMinutes;window.__uxNote=editNote;window.__uxExport=exportData;window.addEventListener('load',()=>setTimeout(()=>{style();navPatch();topLinksPatch();renderPage()},300));window.addEventListener('hashchange',()=>setTimeout(()=>{navPatch();topLinksPatch();renderPage()},50));
})();
